;;; deepsky-modus-theme.el --- Accessibledark themebased on Modus Vivendi -*- lexical-binding:t -*-

;; Copyright (C) 2019-2020 Free Software Foundation, Inc.
;; Copyright (C) 2020 Brian O'Reilly <fade@deepsky.com>

;; Author: Brian O'Reilly <fade@deepsky.com>
;; URL: https://github.com/fade/deepsky-modus-theme.git


(deftheme deepsky-modus-fade
  "Created 2020-12-19 

  This theme is heavily based upon Protesilaos Stavrou's
  <info@protesilaos.com> work in the modus themes. I have
  leveraged the structure of modus-vivendi specifically, so it
  plays to the limitations of my own colour vision more gently.
  Anyhow, many thanks to him, for his work. This theme is also licensed
  under the GPL v3. or at your discretion any later version of that
  license.
")

(defgroup deepsky-theme ()
  "Theme that ensures WCAG AAA accessibility (contrast ratio
between foreground and background is >= 7:1)."
  :group 'faces
  :prefix "deepsky-theme-"
  :link '(url-link :tag "GitHub" "https://github.com/fade/deepsky-modus-theme.git")
  :tag "DeepSky Modus Mashup")

(defface deepsky-theme-subtle-red nil nil)
(defface deepsky-theme-subtle-green nil nil)
(defface deepsky-theme-subtle-yellow nil nil)
(defface deepsky-theme-subtle-blue nil nil)
(defface deepsky-theme-subtle-magenta nil nil)
(defface deepsky-theme-subtle-cyan nil nil)
(defface deepsky-theme-subtle-neutral nil nil)
(defface deepsky-theme-intense-red nil nil)
(defface deepsky-theme-intense-green nil nil)
(defface deepsky-theme-intense-yellow nil nil)
(defface deepsky-theme-intense-blue nil nil)
(defface deepsky-theme-intense-magenta nil nil)
(defface deepsky-theme-intense-cyan nil nil)
(defface deepsky-theme-intense-neutral nil nil)
(defface deepsky-theme-refine-red nil nil)
(defface deepsky-theme-refine-green nil nil)
(defface deepsky-theme-refine-yellow nil nil)
(defface deepsky-theme-refine-blue nil nil)
(defface deepsky-theme-refine-magenta nil nil)
(defface deepsky-theme-refine-cyan nil nil)
(defface deepsky-theme-active-red nil nil)
(defface deepsky-theme-active-green nil nil)
(defface deepsky-theme-active-yellow nil nil)
(defface deepsky-theme-active-blue nil nil)
(defface deepsky-theme-active-magenta nil nil)
(defface deepsky-theme-active-cyan nil nil)
(defface deepsky-theme-fringe-red nil nil)
(defface deepsky-theme-fringe-green nil nil)
(defface deepsky-theme-fringe-yellow nil nil)
(defface deepsky-theme-fringe-blue nil nil)
(defface deepsky-theme-fringe-magenta nil nil)
(defface deepsky-theme-fringe-cyan nil nil)
(defface deepsky-theme-nuanced-red nil nil)
(defface deepsky-theme-nuanced-green nil nil)
(defface deepsky-theme-nuanced-yellow nil nil)
(defface deepsky-theme-nuanced-blue nil nil)
(defface deepsky-theme-nuanced-magenta nil nil)
(defface deepsky-theme-nuanced-cyan nil nil)
(defface deepsky-theme-special-cold nil nil)
(defface deepsky-theme-special-mild nil nil)
(defface deepsky-theme-special-warm nil nil)
(defface deepsky-theme-special-calm nil nil)
(defface deepsky-theme-diff-added nil nil)
(defface deepsky-theme-diff-changed nil nil)
(defface deepsky-theme-diff-removed nil nil)
(defface deepsky-theme-diff-refine-added nil nil)
(defface deepsky-theme-diff-refine-changed nil nil)
(defface deepsky-theme-diff-refine-removed nil nil)
(defface deepsky-theme-diff-focus-added nil nil)
(defface deepsky-theme-diff-focus-changed nil nil)
(defface deepsky-theme-diff-focus-removed nil nil)
(defface deepsky-theme-diff-heading nil nil)
(defface deepsky-theme-pseudo-header nil nil)
(defface deepsky-theme-mark-alt nil nil)
(defface deepsky-theme-mark-del nil nil)
(defface deepsky-theme-mark-sel nil nil)
(defface deepsky-theme-mark-symbol nil nil)
(defface deepsky-theme-heading-1 nil nil)
(defface deepsky-theme-heading-2 nil nil)
(defface deepsky-theme-heading-3 nil nil)
(defface deepsky-theme-heading-4 nil nil)
(defface deepsky-theme-heading-5 nil nil)
(defface deepsky-theme-heading-6 nil nil)
(defface deepsky-theme-heading-7 nil nil)
(defface deepsky-theme-heading-8 nil nil)
(defface deepsky-theme-hl-line nil nil)
(defface deepsky-theme-bold nil nil)
(defface deepsky-theme-slant nil nil)
(defface deepsky-theme-variable-pitch nil nil)

(custom-theme-set-variables
 'deepsky-modus-fade
 '(ansi-color-faces-vector [default bold shadow italic underline success warning error])
 '(ansi-color-names-vector ["#000000" "#ff8059" "#44bc44" "#eecc00" "#2fafff" "#feacd0" "#00d3d0" "#ffffff"])
 '(flymake-error-bitmap ''(flymake-double-exclamation-mark deepsky-theme-fringe-red))
 '(flymake-warning-bitmap ''(exclamation-mark deepsky-theme-fringe-yellow))
 '(flymake-note-bitmap ''(exclamation-mark deepsky-theme-fringe-cyan))
 '(ibuffer-deletion-face ''deepsky-theme-mark-del)
 '(ibuffer-filter-group-name-face ''deepsky-theme-mark-symbol)
 '(ibuffer-marked-face ''deepsky-theme-mark-sel)
 '(ibuffer-title-face ''deepsky-theme-pseudo-header)
 '(pdf-view-midnight-colors ''("#ffffff" . "#110b11")))

(custom-theme-set-faces
 'deepsky-modus-fade
 '(default
    ((t (:family "Envy Code R" :foundry "ENVY" :slant normal :weight normal :height 120 :width normal
                 :foreground "white" :background "black"))))
 '(cursor ((((class color) (min-colors 89)) :background "#ffffff")))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((class color) (min-colors 89)) :foreground "#e7a59a")))
 '(homoglyph ((((class color) (min-colors 89)) :foreground "#e7a59a")))
 '(minibuffer-prompt ((((class color) (min-colors 89)) :background nil :foreground "#6ae4b9")))
 '(highlight ((((class color) (min-colors 89)) :inherit deepsky-theme-subtle-blue)))
 '(region ((((class color) (min-colors 89)) :background "Steelblue4" :foreground "Yellow")))
 '(shadow ((((class color) (min-colors 89)) :foreground "#a8a8a8")))
 '(secondary-selection ((((class color) (min-colors 89)) :inherit deepsky-theme-special-cold)))
 '(trailing-whitespace ((((class color) (min-colors 89)) :background "#a4202a")))
 ;;; fontlock faces
 
 '(font-lock-builtin-face ((t (:foreground "#Ffa500"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "Cyan3"))))
 '(font-lock-comment-face ((t (:foreground "Cyan2"))))
 '(font-lock-constant-face ((t (:foreground "#00ff00"))))
 '(font-lock-doc-face ((t (:foreground "#Ffff00"))))
 '(font-lock-function-name-face ((t (:foreground "SteelBlue"))))
 '(font-lock-keyword-face ((t (:foreground "Cyan3"))))
 '(font-lock-negation-char-face ((t (nil))))
 '(font-lock-preprocessor-face ((t (nil))))
 '(font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
 '(font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
 '(font-lock-string-face ((t (:foreground "#Ffff00"))))
 '(font-lock-type-face ((t (nil))))
 '(font-lock-variable-name-face ((t (:foreground "cyan"))))
 '(font-lock-warning-face ((t (:bold t :foreground "Red" :weight bold))))
;;; /fontlock faces
 '(button ((((class color) (min-colors 89)) :foreground "#00bcff" :underline t)))
 '(link ((((class color) (min-colors 89)) :inherit button)))
 '(link-visited ((((class color) (min-colors 89)) :inherit button :foreground "#b6a0ff")))
 '(fringe ((((class color) (min-colors 89)) :background "#000000" :foreground "#ffffff")))
 '(header-line ((((class color) (min-colors 89)) :background "#212121" :foreground "#dddddd")))
 '(tooltip ((((class color) (min-colors 89)) :background "#203448" :foreground "#ffffff")))
 '(mode-line ((((class color) (min-colors 89)) :foreground "#f4f4f4" :background "#473c8b" :box "#a8a8a8")))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) :inherit bold)))
 '(mode-line-emphasis ((((class color) (min-colors 89)) :inherit bold :foreground "#34cfff")))
 '(mode-line-highlight ((((class color) (min-colors 89)) :inherit deepsky-theme-active-blue :box (:line-width -1 :style pressed-button))))
 '(mode-line-inactive ((((class color) (min-colors 89)) :foreground "#bfc0c4" :background "#2f4f4f" :box "#3c3c3c")))
 '(isearch ((((class color) (min-colors 89)) :inherit (deepsky-theme-intense-green bold))))
 '(isearch-fail ((((class color) (min-colors 89)) :inherit deepsky-theme-refine-red)))
 '(lazy-highlight ((((class color) (min-colors 89)) :inherit deepsky-theme-refine-cyan)))
 '(match ((((class color) (min-colors 89)) :inherit deepsky-theme-special-calm)))
 '(next-error ((((class color) (min-colors 89)) :inherit deepsky-theme-subtle-red)))
 '(query-replace ((((class color) (min-colors 89)) :inherit (deepsky-theme-intense-yellow bold))))
 '(deepsky-theme-subtle-red ((((class color) (min-colors 89)) :background "#762422" :foreground "#e0e6f0")))
 '(deepsky-theme-subtle-green ((((class color) (min-colors 89)) :background "#2f4a00" :foreground "#e0e6f0")))
 '(deepsky-theme-subtle-yellow ((((class color) (min-colors 89)) :background "#604200" :foreground "#e0e6f0")))
 '(deepsky-theme-subtle-blue ((((class color) (min-colors 89)) :background "#10387c" :foreground "#e0e6f0")))
 '(deepsky-theme-subtle-magenta ((((class color) (min-colors 89)) :background "#49366e" :foreground "#e0e6f0")))
 '(deepsky-theme-subtle-cyan ((((class color) (min-colors 89)) :background "#00415e" :foreground "#e0e6f0")))
 '(deepsky-theme-subtle-neutral ((((class color) (min-colors 89)) :background "#1e1e1e" :foreground "#bfc0c4")))
 '(deepsky-theme-intense-red ((((class color) (min-colors 89)) :background "#a4202a" :foreground "#ffffff")))
 '(deepsky-theme-intense-green ((((class color) (min-colors 89)) :background "#006800" :foreground "#ffffff")))
 '(deepsky-theme-intense-yellow ((((class color) (min-colors 89)) :background "#874900" :foreground "#ffffff")))
 '(deepsky-theme-intense-blue ((((class color) (min-colors 89)) :background "#2a40b8" :foreground "#ffffff")))
 '(deepsky-theme-intense-magenta ((((class color) (min-colors 89)) :background "#7042a2" :foreground "#ffffff")))
 '(deepsky-theme-intense-cyan ((((class color) (min-colors 89)) :background "#005f88" :foreground "#ffffff")))
 '(deepsky-theme-intense-neutral ((((class color) (min-colors 89)) :background "#323232" :foreground "#ffffff")))
 '(deepsky-theme-refine-red ((((class color) (min-colors 89)) :background "#77002a" :foreground "#ffb9ab")))
 '(deepsky-theme-refine-green ((((class color) (min-colors 89)) :background "#00422a" :foreground "#9ff0cf")))
 '(deepsky-theme-refine-yellow ((((class color) (min-colors 89)) :background "#693200" :foreground "#e2d980")))
 '(deepsky-theme-refine-blue ((((class color) (min-colors 89)) :background "#242679" :foreground "#8ec6ff")))
 '(deepsky-theme-refine-magenta ((((class color) (min-colors 89)) :background "#71206a" :foreground "#ffcaf0")))
 '(deepsky-theme-refine-cyan ((((class color) (min-colors 89)) :background "#004065" :foreground "#8ae4f2")))
 '(deepsky-theme-active-red ((((class color) (min-colors 89)) :background "#ffa7ba" :foreground "#323232")))
 '(deepsky-theme-active-green ((((class color) (min-colors 89)) :background "#70d73f" :foreground "#323232")))
 '(deepsky-theme-active-yellow ((((class color) (min-colors 89)) :background "#dbbe5f" :foreground "#323232")))
 '(deepsky-theme-active-blue ((((class color) (min-colors 89)) :background "#34cfff" :foreground "#323232")))
 '(deepsky-theme-active-magenta ((((class color) (min-colors 89)) :background "#d5b1ff" :foreground "#323232")))
 '(deepsky-theme-active-cyan ((((class color) (min-colors 89)) :background "#00d8b4" :foreground "#323232")))
 '(deepsky-theme-nuanced-red ((((class color) (min-colors 89)) :background "#2c0614" :extend t)))
 '(deepsky-theme-nuanced-green ((((class color) (min-colors 89)) :background "#001904" :extend t)))
 '(deepsky-theme-nuanced-yellow ((((class color) (min-colors 89)) :background "#221000" :extend t)))
 '(deepsky-theme-nuanced-blue ((((class color) (min-colors 89)) :background "#0f0e39" :extend t)))
 '(deepsky-theme-nuanced-magenta ((((class color) (min-colors 89)) :background "#230631" :extend t)))
 '(deepsky-theme-nuanced-cyan ((((class color) (min-colors 89)) :background "#041529" :extend t)))
 '(deepsky-theme-fringe-red ((((class color) (min-colors 89)) :background "#8f1f4b" :foreground "#ffffff")))
 '(deepsky-theme-fringe-green ((((class color) (min-colors 89)) :background "#006700" :foreground "#ffffff")))
 '(deepsky-theme-fringe-yellow ((((class color) (min-colors 89)) :background "#6f4f00" :foreground "#ffffff")))
 '(deepsky-theme-fringe-blue ((((class color) (min-colors 89)) :background "#3f33af" :foreground "#ffffff")))
 '(deepsky-theme-fringe-magenta ((((class color) (min-colors 89)) :background "#6f2f89" :foreground "#ffffff")))
 '(deepsky-theme-fringe-cyan ((((class color) (min-colors 89)) :background "#004f8f" :foreground "#ffffff")))
 '(deepsky-theme-special-cold ((((class color) (min-colors 89)) :background "#203448" :foreground "#c6eaff")))
 '(deepsky-theme-special-mild ((((class color) (min-colors 89)) :background "#00322e" :foreground "#bfebe0")))
 '(deepsky-theme-special-warm ((((class color) (min-colors 89)) :background "#382f27" :foreground "#f8dec0")))
 '(deepsky-theme-special-calm ((((class color) (min-colors 89)) :background "#392a48" :foreground "#fbd6f4")))
 '(deepsky-theme-diff-added ((((class color) (min-colors 89)) :background "#203d20" :foreground "#b4ddb4")))
 '(deepsky-theme-diff-changed ((((class color) (min-colors 89)) :background "#4a3a10" :foreground "#d0daaf")))
 '(deepsky-theme-diff-removed ((((class color) (min-colors 89)) :background "#5e2526" :foreground "#eebdba")))
 '(deepsky-theme-diff-refine-added ((((class color) (min-colors 89)) :background "#005a36" :foreground "#e0f6e0")))
 '(deepsky-theme-diff-refine-changed ((((class color) (min-colors 89)) :background "#585800" :foreground "#ffffcc")))
 '(deepsky-theme-diff-refine-removed ((((class color) (min-colors 89)) :background "#852828" :foreground "#ffd9eb")))
 '(deepsky-theme-diff-focus-added ((((class color) (min-colors 89)) :background "#203d20" :foreground "#b4ddb4")))
 '(deepsky-theme-diff-focus-changed ((((class color) (min-colors 89)) :background "#4a3a10" :foreground "#d0daaf")))
 '(deepsky-theme-diff-focus-removed ((((class color) (min-colors 89)) :background "#5e2526" :foreground "#eebdba")))
 '(deepsky-theme-diff-heading ((((class color) (min-colors 89)) :background "#304466" :foreground "#dadffe")))
 '(deepsky-theme-pseudo-header ((((class color) (min-colors 89)) :inherit bold :foreground "#ffffff")))
 '(deepsky-theme-mark-alt ((((class color) (min-colors 89)) :inherit bold :background "#3f2210" :foreground "#f0aa20")))
 '(deepsky-theme-mark-del ((((class color) (min-colors 89)) :inherit bold :background "#5a0000" :foreground "#ff99aa")))
 '(deepsky-theme-mark-sel ((((class color) (min-colors 89)) :inherit bold :background "#002f2f" :foreground "#60cfa2")))
 '(deepsky-theme-mark-symbol ((((class color) (min-colors 89)) :inherit bold :foreground "#79a8ff")))
 '(deepsky-theme-heading-1 ((((class color) (min-colors 89)) :inherit (bold default) :foreground "#ffffff")))
 '(deepsky-theme-heading-2 ((((class color) (min-colors 89)) :inherit (bold default) :foreground "#f8dec0")))
 '(deepsky-theme-heading-3 ((((class color) (min-colors 89)) :inherit (bold default) :foreground "#c6eaff")))
 '(deepsky-theme-heading-4 ((((class color) (min-colors 89)) :inherit (bold default) :foreground "#bfebe0")))
 '(deepsky-theme-heading-5 ((((class color) (min-colors 89)) :inherit (bold default) :foreground "#fbd6f4")))
 '(deepsky-theme-heading-6 ((((class color) (min-colors 89)) :inherit (bold default) :foreground "#dfdfb0")))
 '(deepsky-theme-heading-7 ((((class color) (min-colors 89)) :inherit (bold default) :foreground "#ffcccc")))
 '(deepsky-theme-heading-8 ((((class color) (min-colors 89)) :inherit (bold default) :foreground "#e0e6f0")))
 '(deepsky-theme-bold ((((class color) (min-colors 89)))))
 '(deepsky-theme-hl-line ((((class color) (min-colors 89)) :background "#151823" (and (>= emacs-major-version 27) '(:extend t)))))
 '(deepsky-theme-slant ((((class color) (min-colors 89)) :inherit italic :slant normal)))
 '(deepsky-theme-variable-pitch ((((class color) (min-colors 89)))))
 '(vertical-border ((((class color) (min-colors 89)) :foreground "#646464")))
 '(bold ((((class color) (min-colors 89)) :weight bold)))
 '(bold-italic ((((class color) (min-colors 89)) :inherit (bold italic))))
 '(buffer-menu-buffer ((((class color) (min-colors 89)) :inherit bold)))
 '(comint-highlight-input ((((class color) (min-colors 89)) :inherit bold)))
 '(comint-highlight-prompt ((((class color) (min-colors 89)) :inherit deepsky-theme-bold :background nil :foreground "#00d3d0")))
 '(error ((((class color) (min-colors 89)) :inherit bold :foreground "#ff8059")))
 '(file-name-shadow ((((class color) (min-colors 89)) :foreground "#93959b")))
 '(header-line-highlight ((((class color) (min-colors 89)) :inherit deepsky-theme-active-blue)))
 '(help-argument-name ((((class color) (min-colors 89)) :inherit deepsky-theme-slant :foreground "#00d3d0")))
 '(ibuffer-locked-buffer ((((class color) (min-colors 89)) :foreground "#f0ce43")))
 '(italic ((((class color) (min-colors 89)) :slant italic)))
 '(nobreak-hyphen ((((class color) (min-colors 89)) :foreground "#e7a59a")))
 '(nobreak-space ((((class color) (min-colors 89)) :foreground "#e7a59a" :underline t)))
 '(rectangle-preview ((((class color) (min-colors 89)) :inherit deepsky-theme-special-mild)))
 '(success ((((class color) (min-colors 89)) :inherit bold :foreground "#44bc44")))
 '(warning ((((class color) (min-colors 89)) :inherit bold :foreground "#eecc00")))
 '(widget-button ((((class color) (min-colors 89)) :inherit button)))
 '(widget-button-pressed ((((class color) (min-colors 89)) :inherit button :foreground "#feacd0")))
 '(widget-documentation ((((class color) (min-colors 89)) :foreground "#44bc44")))
 '(widget-field ((((class color) (min-colors 89)) :background "#181a20" :foreground "#e0e6f0")))
 '(widget-inactive ((((class color) (min-colors 89)) :background "#1e1e1e" :foreground "#bfc0c4")))
 '(widget-single-line-field ((((class color) (min-colors 89)) :inherit widget-field)))
 '(all-the-icons-blue ((((class color) (min-colors 89)) :foreground "#2fafff")))
 '(all-the-icons-blue-alt ((((class color) (min-colors 89)) :foreground "#79a8ff")))
 '(all-the-icons-cyan ((((class color) (min-colors 89)) :foreground "#00d3d0")))
 '(all-the-icons-cyan-alt ((((class color) (min-colors 89)) :foreground "#4ae8fc")))
 '(all-the-icons-dblue ((((class color) (min-colors 89)) :foreground "#00bcff")))
 '(all-the-icons-dcyan ((((class color) (min-colors 89)) :foreground "#6ae4b9")))
 '(all-the-icons-dgreen ((((class color) (min-colors 89)) :foreground "#00cd68")))
 '(all-the-icons-dmaroon ((((class color) (min-colors 89)) :foreground "#b6a0ff")))
 '(all-the-icons-dorange ((((class color) (min-colors 89)) :foreground "#ff9977")))
 '(all-the-icons-dpink ((((class color) (min-colors 89)) :foreground "#feacd0")))
 '(all-the-icons-dpurple ((((class color) (min-colors 89)) :foreground "#f78fe7")))
 '(all-the-icons-dred ((((class color) (min-colors 89)) :foreground "#ff8059")))
 '(all-the-icons-dsilver ((((class color) (min-colors 89)) :foreground "#c6eaff")))
 '(all-the-icons-dyellow ((((class color) (min-colors 89)) :foreground "#eecc00")))
 '(all-the-icons-green ((((class color) (min-colors 89)) :foreground "#44bc44")))
 '(all-the-icons-lblue ((((class color) (min-colors 89)) :foreground "#8ec6ff")))
 '(all-the-icons-lcyan ((((class color) (min-colors 89)) :foreground "#8ae4f2")))
 '(all-the-icons-lgreen ((((class color) (min-colors 89)) :foreground "#9ff0cf")))
 '(all-the-icons-lmaroon ((((class color) (min-colors 89)) :foreground "#ffcaf0")))
 '(all-the-icons-lorange ((((class color) (min-colors 89)) :foreground "#ffb9ab")))
 '(all-the-icons-lpink ((((class color) (min-colors 89)) :foreground "#ffcaf0")))
 '(all-the-icons-lpurple ((((class color) (min-colors 89)) :foreground "#ffcaf0")))
 '(all-the-icons-lred ((((class color) (min-colors 89)) :foreground "#ffb9ab")))
 '(all-the-icons-lsilver ((((class color) (min-colors 89)) :foreground "#c6eaff")))
 '(all-the-icons-lyellow ((((class color) (min-colors 89)) :foreground "#e2d980")))
 '(all-the-icons-maroon ((((class color) (min-colors 89)) :foreground "#feacd0")))
 '(all-the-icons-orange ((((class color) (min-colors 89)) :foreground "#f4923b")))
 '(all-the-icons-pink ((((class color) (min-colors 89)) :foreground "#feacd0")))
 '(all-the-icons-purple ((((class color) (min-colors 89)) :foreground "#f78fe7")))
 '(all-the-icons-purple-alt ((((class color) (min-colors 89)) :foreground "#b6a0ff")))
 '(all-the-icons-red ((((class color) (min-colors 89)) :foreground "#ff8059")))
 '(all-the-icons-red-alt ((((class color) (min-colors 89)) :foreground "#f4923b")))
 '(all-the-icons-silver ((((class color) (min-colors 89)) :foreground "#c6eaff")))
 '(all-the-icons-yellow ((((class color) (min-colors 89)) :foreground "#eecc00")))
 '(calendar-month-header ((((class color) (min-colors 89)) :inherit bold :foreground "#ffffff")))
 '(calendar-today ((((class color) (min-colors 89)) :underline t)))
 '(calendar-weekday-header ((((class color) (min-colors 89)) :foreground "#e0e6f0")))
 '(calendar-weekend-header ((((class color) (min-colors 89)) :foreground "#a8a8a8")))
 '(diary ((((class color) (min-colors 89)) :foreground "#6ae4b9")))
 '(holiday ((((class color) (min-colors 89)) :foreground "#f78fe7")))
 '(company-echo-common ((((class color) (min-colors 89)) :foreground "#b6a0ff")))
 '(company-preview ((((class color) (min-colors 89)) :background "#110b11" :foreground "#e0e6f0")))
 '(company-preview-common ((((class color) (min-colors 89)) :foreground "#79a8ff")))
 '(company-preview-search ((((class color) (min-colors 89)) :inherit deepsky-theme-special-calm)))
 '(company-scrollbar-bg ((((class color) (min-colors 89)) :background "#323232")))
 '(company-scrollbar-fg ((((class color) (min-colors 89)) :background "#f4f4f4")))
 '(company-template-field ((((class color) (min-colors 89)) :inherit deepsky-theme-intense-magenta)))
 '(company-tooltip ((((class color) (min-colors 89)) :background "#181a20" :foreground "#a8a8a8")))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) :inherit deepsky-theme-slant :foreground "#c6eaff")))
 '(company-tooltip-annotation-selection ((((class color) (min-colors 89)) :inherit bold :foreground "#ffffff")))
 '(company-tooltip-common ((((class color) (min-colors 89)) :inherit bold :foreground "#79a8ff")))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) :foreground "#ffffff")))
 '(company-tooltip-mouse ((((class color) (min-colors 89)) :inherit deepsky-theme-intense-blue)))
 '(company-tooltip-search ((((class color) (min-colors 89)) :inherit (deepsky-theme-refine-cyan bold))))
 '(company-tooltip-search-selection ((((class color) (min-colors 89)) :inherit (deepsky-theme-intense-green bold) :underline t)))
 '(company-tooltip-selection ((((class color) (min-colors 89)) :inherit (deepsky-theme-subtle-cyan bold))))
 '(compilation-column-number ((((class color) (min-colors 89)) :foreground "#b6a0ff")))
 '(compilation-error ((((class color) (min-colors 89)) :inherit deepsky-theme-bold :foreground "#ff8059")))
 '(compilation-info ((((class color) (min-colors 89)) :foreground "#c6eaff")))
 '(compilation-line-number ((((class color) (min-colors 89)) :foreground "#f8dec0")))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) :inherit deepsky-theme-bold :foreground "#34cfff")))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) :inherit deepsky-theme-bold :foreground "#ffa7ba")))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) :inherit deepsky-theme-bold :foreground "#d5b1ff")))
 '(compilation-warning ((((class color) (min-colors 89)) :inherit deepsky-theme-bold :foreground "#eecc00")))
 '(completions-annotations ((((class color) (min-colors 89)) :inherit deepsky-theme-slant :foreground "#c6eaff")))
 '(completions-common-part ((((class color) (min-colors 89)) :foreground "#79a8ff")))
 '(completions-first-difference ((((class color) (min-colors 89)) :inherit bold :foreground "#f78fe7")))
 '(csv-separator-face ((((class color) (min-colors 89)) :background "#203448" :foreground "#ffffff")))
 '(custom-button ((((class color) (min-colors 89)) :box (:line-width 2 :color nil :style released-button) :background "#323232" :foreground "#ffffff")))
 '(custom-button-mouse ((((class color) (min-colors 89)) :box (:line-width 2 :color nil :style released-button) :background "#323232" :foreground "#f4f4f4")))
 '(custom-button-pressed ((((class color) (min-colors 89)) :box (:line-width 2 :color nil :style pressed-button) :background "#323232" :foreground "#ffffff")))
 '(custom-changed ((((class color) (min-colors 89)) :inherit deepsky-theme-subtle-cyan)))
 '(custom-comment ((((class color) (min-colors 89)) :foreground "#a8a8a8")))
 '(custom-comment-tag ((((class color) (min-colors 89)) :background "#181a20" :foreground "#f0ce43")))
 '(custom-face-tag ((((class color) (min-colors 89)) :inherit bold :foreground "#00a2ff")))
 '(custom-group-tag ((((class color) (min-colors 89)) :inherit bold :foreground "#00fc50")))
 '(custom-group-tag-1 ((((class color) (min-colors 89)) :inherit deepsky-theme-special-warm)))
 '(custom-invalid ((((class color) (min-colors 89)) :inherit (deepsky-theme-intense-red bold))))
 '(custom-modified ((((class color) (min-colors 89)) :inherit deepsky-theme-subtle-cyan)))
 '(custom-rogue ((((class color) (min-colors 89)) :inherit deepsky-theme-refine-magenta)))
 '(custom-set ((((class color) (min-colors 89)) :foreground "#79a8ff")))
 '(custom-state ((((class color) (min-colors 89)) :foreground "#6ae4b9")))
 '(custom-themed ((((class color) (min-colors 89)) :inherit deepsky-theme-subtle-blue)))
 '(custom-variable-tag ((((class color) (min-colors 89)) :inherit bold :foreground "#00d3d0")))
 '(dashboard-banner-logo-title ((((class color) (min-colors 89)) :inherit bold :foreground "#c6eaff")))
 '(dashboard-footer ((((class color) (min-colors 89)) :inherit bold :foreground "#bfebe0")))
 '(dashboard-heading ((((class color) (min-colors 89)) :inherit bold :foreground "#f8dec0")))
 '(dashboard-navigator ((((class color) (min-colors 89)) :foreground "#6ae4b9")))
 '(dashboard-text-banner ((((class color) (min-colors 89)) :foreground "#e0e6f0")))
 '(diff-added ((((class color) (min-colors 89)) :inherit deepsky-theme-diff-added)))
 '(diff-changed ((((class color) (min-colors 89)) :inherit deepsky-theme-diff-changed)))
 '(diff-context ((((class color) (min-colors 89)) :foreground "#93959b")))
 '(diff-file-header ((((class color) (min-colors 89)) :inherit bold :foreground "#ffffff")))
 '(diff-function ((((class color) (min-colors 89)) :foreground "#2fafff")))
 '(diff-header ((((class color) (min-colors 89)) :background "#110b11" :foreground "#ffffff")))
 '(diff-hunk-header ((((class color) (min-colors 89)) :inherit deepsky-theme-diff-heading)))
 '(diff-index ((((class color) (min-colors 89)) :inherit bold :foreground "#79a8ff")))
 '(diff-indicator-added ((((class color) (min-colors 89)) :inherit diff-added)))
 '(diff-indicator-changed ((((class color) (min-colors 89)) :inherit diff-changed)))
 '(diff-indicator-removed ((((class color) (min-colors 89)) :inherit diff-removed)))
 '(diff-nonexistent ((((class color) (min-colors 89)) :inherit (deepsky-theme-neutral bold))))
 '(diff-refine-added ((((class color) (min-colors 89)) :inherit deepsky-theme-diff-refine-added)))
 '(diff-refine-changed ((((class color) (min-colors 89)) :inherit deepsky-theme-diff-refine-changed)))
 '(diff-refine-removed ((((class color) (min-colors 89)) :inherit deepsky-theme-diff-refine-removed)))
 '(diff-removed ((((class color) (min-colors 89)) :inherit deepsky-theme-diff-removed)))
 '(dired-directory ((((class color) (min-colors 89)) :foreground "#2fafff")))
 '(dired-flagged ((((class color) (min-colors 89)) :inherit deepsky-theme-mark-del)))
 '(dired-header ((((class color) (min-colors 89)) :inherit deepsky-theme-pseudo-header)))
 '(dired-ignored ((((class color) (min-colors 89)) :foreground "#a8a8a8")))
 '(dired-mark ((((class color) (min-colors 89)) :inherit deepsky-theme-mark-symbol)))
 '(dired-marked ((((class color) (min-colors 89)) :inherit deepsky-theme-mark-sel)))
 '(dired-perm-write ((((class color) (min-colors 89)) :foreground "#f8dec0")))
 '(dired-symlink ((((class color) (min-colors 89)) :inherit button :foreground "#4ae8fc")))
 '(dired-warning ((((class color) (min-colors 89)) :inherit bold :foreground "#eecc00")))
 '(eldoc-highlight-function-argument ((((class color) (min-colors 89)) :inherit bold :foreground "#00bcff")))
 '(flycheck-error ((((supports :underline (:style wave)) (class color) (min-colors 89)) :underline (:color "#ef8690" :style wave)) (((class color) (min-colors 89)) :foreground "#ef8690" :underline t)))
 '(flycheck-error-list-checker-name ((((class color) (min-colors 89)) :foreground "#d5b1ff")))
 '(flycheck-error-list-column-number ((((class color) (min-colors 89)) :foreground "#c6eaff")))
 '(flycheck-error-list-error ((((class color) (min-colors 89)) :inherit deepsky-theme-bold :foreground "#ff8059")))
 '(flycheck-error-list-filename ((((class color) (min-colors 89)) :foreground "#2fafff")))
 '(flycheck-error-list-highlight ((((class color) (min-colors 89)) :inherit deepsky-theme-hl-line)))
 '(flycheck-error-list-id ((((class color) (min-colors 89)) :foreground "#b6a0ff")))
 '(flycheck-error-list-id-with-explainer ((((class color) (min-colors 89)) :inherit flycheck-error-list-id :box t)))
 '(flycheck-error-list-info ((((class color) (min-colors 89)) :foreground "#00d3d0")))
 '(flycheck-error-list-line-number ((((class color) (min-colors 89)) :foreground "#f8dec0")))
 '(flycheck-error-list-warning ((((class color) (min-colors 89)) :foreground "#eecc00")))
 '(flycheck-fringe-error ((((class color) (min-colors 89)) :inherit deepsky-theme-fringe-red)))
 '(flycheck-fringe-info ((((class color) (min-colors 89)) :inherit deepsky-theme-fringe-cyan)))
 '(flycheck-fringe-warning ((((class color) (min-colors 89)) :inherit deepsky-theme-fringe-yellow)))
 '(flycheck-info ((((supports :underline (:style wave)) (class color) (min-colors 89)) :underline (:color "#9d9def" :style wave)) (((class color) (min-colors 89)) :foreground "#9d9def" :underline t)))
 '(flycheck-verify-select-checker ((((class color) (min-colors 89)) :box (:line-width 1 :color nil :style released-button))))
 '(flycheck-warning ((((supports :underline (:style wave)) (class color) (min-colors 89)) :underline (:color "#b0aa00" :style wave)) (((class color) (min-colors 89)) :foreground "#b0aa00" :underline t)))
 '(flymake-error ((((supports :underline (:style wave)) (class color) (min-colors 89)) :underline (:color "#ef8690" :style wave)) (((class color) (min-colors 89)) :foreground "#ef8690" :underline t)))
 '(flymake-note ((((supports :underline (:style wave)) (class color) (min-colors 89)) :underline (:color "#9d9def" :style wave)) (((class color) (min-colors 89)) :foreground "#9d9def" :underline t)))
 '(flymake-warning ((((supports :underline (:style wave)) (class color) (min-colors 89)) :underline (:color "#b0aa00" :style wave)) (((class color) (min-colors 89)) :foreground "#b0aa00" :underline t)))
 '(helm-M-x-key ((((class color) (min-colors 89)) :inherit bold :foreground "#b6a0ff")))
 '(helm-action ((((class color) (min-colors 89)) :underline t)))
 '(helm-buffer-archive ((((class color) (min-colors 89)) :inherit bold :foreground "#00d3d0")))
 '(helm-buffer-directory ((((class color) (min-colors 89)) :inherit bold :foreground "#2fafff")))
 '(helm-buffer-file ((((class color) (min-colors 89)) :foreground "#ffffff")))
 '(helm-buffer-modified ((((class color) (min-colors 89)) :foreground "#cfdf30")))
 '(helm-buffer-not-saved ((((class color) (min-colors 89)) :foreground "#f4923b")))
 '(helm-buffer-process ((((class color) (min-colors 89)) :foreground "#feacd0")))
 '(helm-buffer-saved-out ((((class color) (min-colors 89)) :inherit bold :background "#181a20" :foreground "#ff8059")))
 '(helm-buffer-size ((((class color) (min-colors 89)) :foreground "#a8a8a8")))
 '(helm-candidate-number ((((class color) (min-colors 89)) :foreground "#00d8b4")))
 '(helm-candidate-number-suspended ((((class color) (min-colors 89)) :foreground "#dbbe5f")))
 '(helm-delete-async-message ((((class color) (min-colors 89)) :inherit bold :foreground "#d5b1ff")))
 '(helm-eob-line ((((class color) (min-colors 89)) :background "#000000" :foreground "#ffffff")))
 '(helm-etags-file ((((class color) (min-colors 89)) :foreground "#e0e6f0" :underline t)))
 '(helm-ff-backup-file ((((class color) (min-colors 89)) :foreground "#a8a8a8")))
 '(helm-ff-denied ((((class color) (min-colors 89)) :inherit (deepsky-theme-intense-red nil))))
 '(helm-ff-directory ((((class color) (min-colors 89)) :inherit helm-buffer-directory)))
 '(helm-ff-dirs ((((class color) (min-colors 89)) :inherit bold :foreground "#00bcff")))
 '(helm-ff-dotted-directory ((((class color) (min-colors 89)) :inherit bold :background "#181a20" :foreground "#a8a8a8")))
 '(helm-ff-dotted-symlink-directory ((((class color) (min-colors 89)) :inherit (button helm-ff-dotted-directory))))
 '(helm-ff-executable ((((class color) (min-colors 89)) :foreground "#f78fe7")))
 '(helm-ff-file ((((class color) (min-colors 89)) :foreground "#ffffff")))
 '(helm-ff-file-extension ((((class color) (min-colors 89)) :foreground "#f8dec0")))
 '(helm-ff-invalid-symlink ((((class color) (min-colors 89)) :inherit button :foreground "#ff8059")))
 '(helm-ff-pipe ((((class color) (min-colors 89)) :inherit (deepsky-theme-subtle-magenta nil))))
 '(helm-ff-prefix ((((class color) (min-colors 89)) :inherit (deepsky-theme-subtle-yellow nil))))
 '(helm-ff-socket ((((class color) (min-colors 89)) :foreground "#ff9977")))
 '(helm-ff-suid ((((class color) (min-colors 89)) :inherit (deepsky-theme-refine-red nil))))
 '(helm-ff-symlink ((((class color) (min-colors 89)) :inherit button :foreground "#00d3d0")))
 '(helm-ff-truename ((((class color) (min-colors 89)) :foreground "#00bcff")))
 '(helm-grep-cmd-line ((((class color) (min-colors 89)) :foreground "#f0ce43")))
 '(helm-grep-file ((((class color) (min-colors 89)) :inherit bold :foreground "#c6eaff")))
 '(helm-grep-finish ((((class color) (min-colors 89)) :foreground "#70d73f")))
 '(helm-grep-lineno ((((class color) (min-colors 89)) :foreground "#f8dec0")))
 '(helm-grep-match ((((class color) (min-colors 89)) :inherit deepsky-theme-special-calm)))
 '(helm-header ((((class color) (min-colors 89)) :inherit bold :foreground "#c6eaff")))
 '(helm-header-line-left-margin ((((class color) (min-colors 89)) :inherit bold :foreground "#ffdd00")))
 '(helm-history-deleted ((((class color) (min-colors 89)) :inherit (deepsky-theme-intense-red bold))))
 '(helm-history-remote ((((class color) (min-colors 89)) :foreground "#ff9977")))
 '(helm-lisp-completion-info ((((class color) (min-colors 89)) :foreground "#f8dec0")))
 '(helm-lisp-show-completion ((((class color) (min-colors 89)) :inherit (deepsky-theme-refine-yellow bold))))
 '(helm-locate-finish ((((class color) (min-colors 89)) :foreground "#70d73f")))
 '(helm-match ((((class color) (min-colors 89)) :inherit (deepsky-theme-refine-cyan bold))))
 '(helm-match-item ((((class color) (min-colors 89)) :inherit (deepsky-theme-subtle-cyan nil))))
 '(helm-minibuffer-prompt ((((class color) (min-colors 89)) :inherit minibuffer-prompt)))
 '(helm-moccur-buffer ((((class color) (min-colors 89)) :inherit button :foreground "#6ae4b9")))
 '(helm-mode-prefix ((((class color) (min-colors 89)) :inherit (deepsky-theme-intense-magenta bold))))
 '(helm-non-file-buffer ((((class color) (min-colors 89)) :foreground "#a8a8a8")))
 '(helm-prefarg ((((class color) (min-colors 89)) :foreground "#ffa7ba")))
 '(helm-resume-need-update ((((class color) (min-colors 89)) :inherit (deepsky-theme-refine-magenta nil))))
 '(helm-selection ((((class color) (min-colors 89)) :inherit (deepsky-theme-refine-blue bold))))
 '(helm-selection-line ((((class color) (min-colors 89)) :inherit deepsky-theme-special-cold)))
 '(helm-separator ((((class color) (min-colors 89)) :foreground "#bfebe0")))
 '(helm-source-header ((((class color) (min-colors 89)) :inherit bold :foreground "#f4923b")))
 '(helm-visible-mark ((((class color) (min-colors 89)) :inherit deepsky-theme-subtle-cyan)))
 '(helpful-heading ((((class color) (min-colors 89)) :inherit deepsky-theme-heading-1)))
 '(hl-line ((((class color) (min-colors 89)) :inherit deepsky-theme-hl-line)))
 '(highlight-indentation-face ((((class color) (min-colors 89)) :inherit deepsky-theme-hl-line)))
 '(highlight-indentation-current-column-face ((((class color) (min-colors 89)) :background "#323232")))
 '(ido-first-match ((((class color) (min-colors 89)) :inherit bold :foreground "#feacd0")))
 '(ido-incomplete-regexp ((((class color) (min-colors 89)) :inherit error)))
 '(ido-indicator ((((class color) (min-colors 89)) :inherit deepsky-theme-subtle-yellow)))
 '(ido-only-match ((((class color) (min-colors 89)) :inherit bold :foreground "#44bc44")))
 '(ido-subdir ((((class color) (min-colors 89)) :foreground "#2fafff")))
 '(ido-virtual ((((class color) (min-colors 89)) :foreground "#f8dec0")))
 '(Info-quoted ((((class color) (min-colors 89)) :inherit fixed-pitch :foreground "#feacd0")))
 '(info-header-node ((((class color) (min-colors 89)) :inherit bold :foreground "#a8a8a8")))
 '(info-header-xref ((((class color) (min-colors 89)) :foreground "#34cfff")))
 '(info-index-match ((((class color) (min-colors 89)) :inherit match)))
 '(info-menu-header ((((class color) (min-colors 89)) :inherit deepsky-theme-heading-3)))
 '(info-menu-star ((((class color) (min-colors 89)) :foreground "#ff8059")))
 '(info-node ((((class color) (min-colors 89)) :inherit bold)))
 '(info-title-1 ((((class color) (min-colors 89)) :inherit deepsky-theme-heading-1)))
 '(info-title-2 ((((class color) (min-colors 89)) :inherit deepsky-theme-heading-2)))
 '(info-title-3 ((((class color) (min-colors 89)) :inherit deepsky-theme-heading-3)))
 '(info-title-4 ((((class color) (min-colors 89)) :inherit deepsky-theme-heading-4)))
 '(ivy-action ((((class color) (min-colors 89)) :inherit bold :foreground "#f4923b")))
 '(ivy-completions-annotations ((((class color) (min-colors 89)) :inherit deepsky-theme-slant :foreground "#c6eaff")))
 '(ivy-confirm-face ((((class color) (min-colors 89)) :foreground "#00d3d0")))
 '(ivy-current-match ((((class color) (min-colors 89)) :inherit (deepsky-theme-intense-cyan bold))))
 '(ivy-cursor ((((class color) (min-colors 89)) :background "#ffffff" :foreground "#000000")))
 '(ivy-grep-info ((((class color) (min-colors 89)) :foreground "#4ae8fc")))
 '(ivy-grep-line-number ((((class color) (min-colors 89)) :foreground "#f8dec0")))
 '(ivy-highlight-face ((((class color) (min-colors 89)) :foreground "#feacd0")))
 '(ivy-match-required-face ((((class color) (min-colors 89)) :inherit error)))
 '(ivy-minibuffer-match-face-1 ((((class color) (min-colors 89)) :inherit (deepsky-theme-intense-neutral nil))))
 '(ivy-minibuffer-match-face-2 ((((class color) (min-colors 89)) :inherit (deepsky-theme-refine-green bold))))
 '(ivy-minibuffer-match-face-3 ((((class color) (min-colors 89)) :inherit (deepsky-theme-refine-cyan bold))))
 '(ivy-minibuffer-match-face-4 ((((class color) (min-colors 89)) :inherit (deepsky-theme-refine-magenta bold))))
 '(ivy-minibuffer-match-highlight ((((class color) (min-colors 89)) :inherit (deepsky-theme-intense-blue bold))))
 '(ivy-modified-buffer ((((class color) (min-colors 89)) :inherit deepsky-theme-slant :foreground "#eecc00")))
 '(ivy-modified-outside-buffer ((((class color) (min-colors 89)) :inherit deepsky-theme-slant :foreground "#cfdf30")))
 '(ivy-org ((((class color) (min-colors 89)) :foreground "#6ae4b9")))
 '(ivy-prompt-match ((((class color) (min-colors 89)) :inherit ivy-current-match)))
 '(ivy-remote ((((class color) (min-colors 89)) :foreground "#feacd0")))
 '(ivy-separator ((((class color) (min-colors 89)) :foreground "#a8a8a8")))
 '(ivy-subdir ((((class color) (min-colors 89)) :foreground "#00bcff")))
 '(ivy-virtual ((((class color) (min-colors 89)) :foreground "#b6a0ff")))
 '(ivy-yanked-word ((((class color) (min-colors 89)) :inherit (deepsky-theme-refine-blue nil))))
 '(js2-error ((((class color) (min-colors 89)) :foreground "#ff8059")))
 '(js2-external-variable ((((class color) (min-colors 89)) :foreground "#6ae4b9")))
 '(js2-function-call ((((class color) (min-colors 89)) :foreground "#feacd0")))
 '(js2-function-param ((((class color) (min-colors 89)) :foreground "#2fafff")))
 '(js2-instance-member ((((class color) (min-colors 89)) :foreground "#b6a0ff")))
 '(js2-jsdoc-html-tag-delimiter ((((class color) (min-colors 89)) :foreground "#ffffff")))
 '(js2-jsdoc-html-tag-name ((((class color) (min-colors 89)) :foreground "#00d3d0")))
 '(js2-jsdoc-tag ((((class color) (min-colors 89)) :foreground "#fbd6f4")))
 '(js2-jsdoc-type ((((class color) (min-colors 89)) :foreground "#c6eaff")))
 '(js2-jsdoc-value ((((class color) (min-colors 89)) :foreground "#f8dec0")))
 '(js2-object-property ((((class color) (min-colors 89)) :foreground "#ffffff")))
 '(js2-object-property-access ((((class color) (min-colors 89)) :foreground "#ffffff")))
 '(js2-private-function-call ((((class color) (min-colors 89)) :foreground "#00cd68")))
 '(js2-private-member ((((class color) (min-colors 89)) :foreground "#bfebe0")))
 '(js2-warning ((((class color) (min-colors 89)) :foreground "#cfdf30" :underline t)))
 '(line-number ((((class color) (min-colors 89)) :inherit default :background "#110b11" :foreground "#a8a8a8")))
 '(line-number-current-line ((((class color) (min-colors 89)) :inherit default :background "#323232" :foreground "#ffffff")))
 '(mc/cursor-bar-face ((((class color) (min-colors 89)) :height 1 :background "#ffffff")))
 '(mc/cursor-face ((((class color) (min-colors 89)) :inverse-video t)))
 '(mc/region-face ((((class color) (min-colors 89)) :inherit region)))
 '(org-agenda-calendar-event ((((class color) (min-colors 89)) :foreground "#ffffff")))
 '(org-agenda-calendar-sexp ((((class color) (min-colors 89)) :foreground "#4ae8fc")))
 '(org-agenda-clocking ((((class color) (min-colors 89)) :inherit deepsky-theme-special-cold :extend t)))
 '(org-agenda-column-dateline ((((class color) (min-colors 89)) :background "#181a20")))
 '(org-agenda-current-time ((((class color) (min-colors 89)) :inherit bold :foreground "#00bcff")))
 '(org-agenda-date ((((class color) (min-colors 89)) :foreground "#00d3d0")))
 '(org-agenda-date-today ((((class color) (min-colors 89)) :inherit bold :foreground "#ffffff" :underline t)))
 '(org-agenda-date-weekend ((((class color) (min-colors 89)) :foreground "#6ae4b9")))
 '(org-agenda-diary ((((class color) (min-colors 89)) :foreground "#ffffff")))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 89)) :inherit bold :foreground "#a8a8a8")))
 '(org-agenda-done ((((class color) (min-colors 89)) :foreground "#80d200")))
 '(org-agenda-filter-category ((((class color) (min-colors 89)) :inherit bold :foreground "#d5b1ff")))
 '(org-agenda-filter-effort ((((class color) (min-colors 89)) :inherit bold :foreground "#d5b1ff")))
 '(org-agenda-filter-regexp ((((class color) (min-colors 89)) :inherit bold :foreground "#d5b1ff")))
 '(org-agenda-filter-tags ((((class color) (min-colors 89)) :inherit bold :foreground "#d5b1ff")))
 '(org-agenda-restriction-lock ((((class color) (min-colors 89)) :background "#110b11" :foreground "#e0e6f0")))
 '(org-agenda-structure ((((class color) (min-colors 89)) :foreground "#79a8ff")))
 '(org-archived ((((class color) (min-colors 89)) :background "#181a20" :foreground "#a8a8a8")))
 '(org-block ((((class color) (min-colors 89)) :inherit fixed-pitch :background nil :foreground "#ffffff")))
 '(org-block-begin-line ((((class color) (min-colors 89)) :inherit fixed-pitch :background "#181a20" :foreground "#bfebe0")))
 '(org-block-end-line ((((class color) (min-colors 89)) :inherit org-block-begin-line)))
 '(org-checkbox ((((class color) (min-colors 89)) :box (:line-width 1 :color "#323232") :background "#1e1e1e" :foreground "#f4f4f4")))
 '(org-checkbox-statistics-done ((((class color) (min-colors 89)) :inherit org-done)))
 '(org-checkbox-statistics-todo ((((class color) (min-colors 89)) :inherit org-todo)))
 '(org-clock-overlay ((((class color) (min-colors 89)) :inherit deepsky-theme-special-cold)))
 '(org-code ((((class color) (min-colors 89)) :inherit fixed-pitch :foreground "#feacd0")))
 '(org-column ((((class color) (min-colors 89)) :background "#181a20")))
 '(org-column-title ((((class color) (min-colors 89)) :inherit bold :underline t :background "#181a20")))
 '(org-date ((((class color) (min-colors 89)) :inherit (button fixed-pitch) :foreground "#00d3d0")))
 '(org-date-selected ((((class color) (min-colors 89)) :inherit bold :foreground "#79a8ff" :inverse-video t)))
 '(org-document-info ((((class color) (min-colors 89)) :foreground "#c6eaff")))
 '(org-document-info-keyword ((((class color) (min-colors 89)) :inherit fixed-pitch :foreground "#a8a8a8")))
 '(org-document-title ((((class color) (min-colors 89)) :inherit (bold deepsky-theme-variable-pitch) :foreground "#c6eaff")))
 '(org-done ((((class color) (min-colors 89)) :foreground "#44bc44")))
 '(org-drawer ((((class color) (min-colors 89)) :inherit fixed-pitch :foreground "#a8a8a8")))
 '(org-ellipsis ((((class color) (min-colors 89)) :foreground nil)))
 '(org-footnote ((((class color) (min-colors 89)) :inherit button :foreground "#79a8ff")))
 '(org-formula ((((class color) (min-colors 89)) :inherit fixed-pitch :foreground "#f4923b")))
 '(org-headline-done ((((class color) (min-colors 89)) :inherit deepsky-theme-variable-pitch :foreground "#b8e2b8")))
 '(org-headline-todo ((((class color) (min-colors 89)) :inherit deepsky-theme-variable-pitch :foreground "#ffcccc")))
 '(org-hide ((((class color) (min-colors 89)) :foreground "#000000")))
 '(org-latex-and-related ((((class color) (min-colors 89)) :foreground "#ffcaf0")))
 '(org-level-1 ((((class color) (min-colors 89)) :inherit deepsky-theme-heading-1)))
 '(org-level-2 ((((class color) (min-colors 89)) :inherit deepsky-theme-heading-2)))
 '(org-level-3 ((((class color) (min-colors 89)) :inherit deepsky-theme-heading-3)))
 '(org-level-4 ((((class color) (min-colors 89)) :inherit deepsky-theme-heading-4)))
 '(org-level-5 ((((class color) (min-colors 89)) :inherit deepsky-theme-heading-5)))
 '(org-level-6 ((((class color) (min-colors 89)) :inherit deepsky-theme-heading-6)))
 '(org-level-7 ((((class color) (min-colors 89)) :inherit deepsky-theme-heading-7)))
 '(org-level-8 ((((class color) (min-colors 89)) :inherit deepsky-theme-heading-8)))
 '(org-link ((((class color) (min-colors 89)) :inherit button)))
 '(org-list-dt ((((class color) (min-colors 89)) :inherit bold)))
 '(org-macro ((((class color) (min-colors 89)) :background "#0f0e39" :foreground "#b6a0ff")))
 '(org-meta-line ((((class color) (min-colors 89)) :inherit fixed-pitch :foreground "#a8a8a8")))
 '(org-mode-line-clock ((((class color) (min-colors 89)) :foreground "#ffffff")))
 '(org-mode-line-clock-overrun ((((class color) (min-colors 89)) :inherit deepsky-theme-active-red)))
 '(org-priority ((((class color) (min-colors 89)) :foreground "#feacd0")))
 '(org-property-value ((((class color) (min-colors 89)) :inherit fixed-pitch :foreground "#c6eaff")))
 '(org-quote ((((class color) (min-colors 89)) :inherit deepsky-theme-slant :background nil :foreground "#c6eaff")))
 '(org-scheduled ((((class color) (min-colors 89)) :foreground "#f8dec0")))
 '(org-scheduled-previously ((((class color) (min-colors 89)) :foreground "#f0ce43")))
 '(org-scheduled-today ((((class color) (min-colors 89)) :foreground "#b6a0ff")))
 '(org-sexp-date ((((class color) (min-colors 89)) :inherit org-date)))
 '(org-special-keyword ((((class color) (min-colors 89)) :inherit fixed-pitch :foreground "#a8a8a8")))
 '(org-table ((((class color) (min-colors 89)) :inherit fixed-pitch :foreground "#c6eaff")))
 '(org-table-header ((((class color) (min-colors 89)) :inherit (fixed-pitch deepsky-theme-intense-neutral))))
 '(org-tag ((((class color) (min-colors 89)) :foreground "#e5cfef")))
 '(org-tag-group ((((class color) (min-colors 89)) :inherit bold :foreground "#a8e5e5")))
 '(org-target ((((class color) (min-colors 89)) :underline t)))
 '(org-time-grid ((((class color) (min-colors 89)) :foreground "#93959b")))
 '(org-todo ((((class color) (min-colors 89)) :foreground "#ff8059")))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) :foreground "#ff9977")))
 '(org-upcoming-distant-deadline ((((class color) (min-colors 89)) :foreground "#ffcccc")))
 '(org-verbatim ((((class color) (min-colors 89)) :inherit fixed-pitch :background "#181a20" :foreground "#fbd6f4")))
 '(org-verse ((((class color) (min-colors 89)) :inherit org-quote)))
 '(org-warning ((((class color) (min-colors 89)) :inherit bold :foreground "#ff9977")))
 '(org-roam-link ((((class color) (min-colors 89)) :inherit button :foreground "#44bc44")))
 '(org-roam-link-current ((((class color) (min-colors 89)) :inherit button :foreground "#80d200")))
 '(org-roam-link-invalid ((((class color) (min-colors 89)) :inherit button :foreground "#ff8059")))
 '(org-roam-link-shielded ((((class color) (min-colors 89)) :inherit button :foreground "#eecc00")))
 '(org-roam-tag ((((class color) (min-colors 89)) :inherit italic :foreground "#a8a8a8")))
 '(outline-1 ((((class color) (min-colors 89)) :inherit deepsky-theme-heading-1)))
 '(outline-2 ((((class color) (min-colors 89)) :inherit deepsky-theme-heading-2)))
 '(outline-3 ((((class color) (min-colors 89)) :inherit deepsky-theme-heading-3)))
 '(outline-4 ((((class color) (min-colors 89)) :inherit deepsky-theme-heading-4)))
 '(outline-5 ((((class color) (min-colors 89)) :inherit deepsky-theme-heading-5)))
 '(outline-6 ((((class color) (min-colors 89)) :inherit deepsky-theme-heading-6)))
 '(outline-7 ((((class color) (min-colors 89)) :inherit deepsky-theme-heading-7)))
 '(outline-8 ((((class color) (min-colors 89)) :inherit deepsky-theme-heading-8)))
 '(package-description ((((class color) (min-colors 89)) :foreground "#c6eaff")))
 '(package-help-section-name ((((class color) (min-colors 89)) :inherit bold :foreground "#b6a0ff")))
 '(package-name ((((class color) (min-colors 89)) :inherit button)))
 '(package-status-avail-obso ((((class color) (min-colors 89)) :inherit bold :foreground "#ff8059")))
 '(package-status-available ((((class color) (min-colors 89)) :foreground "#bfebe0")))
 '(package-status-built-in ((((class color) (min-colors 89)) :foreground "#feacd0")))
 '(package-status-dependency ((((class color) (min-colors 89)) :foreground "#b6a0ff")))
 '(package-status-disabled ((((class color) (min-colors 89)) :inherit deepsky-theme-subtle-red)))
 '(package-status-external ((((class color) (min-colors 89)) :foreground "#6ae4b9")))
 '(package-status-held ((((class color) (min-colors 89)) :foreground "#cfdf30")))
 '(package-status-incompat ((((class color) (min-colors 89)) :inherit bold :foreground "#eecc00")))
 '(package-status-installed ((((class color) (min-colors 89)) :foreground "#f8dec0")))
 '(package-status-new ((((class color) (min-colors 89)) :inherit bold :foreground "#44bc44")))
 '(package-status-unsigned ((((class color) (min-colors 89)) :inherit bold :foreground "#f4923b")))
 '(page-break-lines ((((class color) (min-colors 89)) :inherit default :foreground "#969696")))
 '(popup-face ((((class color) (min-colors 89)) :background "#181a20" :foreground "#ffffff")))
 '(popup-isearch-match ((((class color) (min-colors 89)) :inherit (deepsky-theme-refine-cyan bold))))
 '(popup-menu-mouse-face ((((class color) (min-colors 89)) :inherit deepsky-theme-intense-blue)))
 '(popup-menu-selection-face ((((class color) (min-colors 89)) :inherit (deepsky-theme-subtle-cyan bold))))
 '(popup-scroll-bar-background-face ((((class color) (min-colors 89)) :background "#323232")))
 '(popup-scroll-bar-foreground-face ((((class color) (min-colors 89)) :foreground "#f4f4f4")))
 '(popup-summary-face ((((class color) (min-colors 89)) :background "#323232" :foreground "#bfc0c4")))
 '(popup-tip-face ((((class color) (min-colors 89)) :inherit deepsky-theme-special-warm)))
 '(powerline-active0 ((((class color) (min-colors 89)) :background "#000000" :foreground "#92baff" :inverse-video t)))
 '(powerline-active1 ((((class color) (min-colors 89)) :background "#0f0e39" :foreground "#bfd9ff")))
 '(powerline-active2 ((((class color) (min-colors 89)) :background "#323232" :foreground "#f4f4f4")))
 '(powerline-inactive0 ((((class color) (min-colors 89)) :background "#203448" :foreground "#c6eaff")))
 '(powerline-inactive1 ((((class color) (min-colors 89)) :background "#110b11" :foreground "#bfc0c4")))
 '(powerline-inactive2 ((((class color) (min-colors 89)) :background "#1e1e1e" :foreground "#bfc0c4")))
 '(semantic-highlight-edits-face ((((class color) (min-colors 89)) :background "#181a20")))
 '(semantic-highlight-func-current-tag-face ((((class color) (min-colors 89)) :background "#181a20")))
 '(semantic-unmatched-syntax-face ((((class color) (min-colors 89)) :underline "#ef8690")))
 '(sesman-browser-button-face ((((class color) (min-colors 89)) :foreground "#00bcff" :underline t)))
 '(sesman-browser-highligh-face ((((class color) (min-colors 89)) :inherit deepsky-theme-subtle-blue)))
 '(sesman-buffer-face ((((class color) (min-colors 89)) :foreground "#feacd0")))
 '(sesman-directory-face ((((class color) (min-colors 89)) :inherit bold :foreground "#2fafff")))
 '(sesman-project-face ((((class color) (min-colors 89)) :inherit bold :foreground "#b6a0ff")))
 '(show-paren-match ((((class color) (min-colors 89)) :background "Magenta" :foreground "#ffffff")))
 '(show-paren-match-expression ((((class color) (min-colors 89)) :inherit deepsky-theme-special-calm)))
 '(show-paren-mismatch ((((class color) (min-colors 89)) :inherit deepsky-theme-intense-red)))
 '(skewer-error-face ((((class color) (min-colors 89)) :foreground "#ff8059" :underline t)))

;;; SLY REPL colors.
 '(sly-error-face ((t (:underline "red"))))
 '(sly-highlight-edits-face ((t (:background "dimgray"))))
 '(sly-highlight-face ((t (:foreground "yellow" :background "SteelBlue" :underline nil))))
 '(sly-inspector-action-face ((t (:bold t :weight bold :foreground "#8b2252"))))
 '(sly-inspector-label-face ((t (:foreground "#00ff00"))))
 '(sly-inspector-topline-face ((t (nil))))
 '(sly-inspector-type-face ((t (nil))))
 '(sly-inspector-value-face ((t (:foreground "#ffaa00"))))
 '(sly-note-face ((t (:underline "light goldenrod"))))
 '(sly-reader-conditional-face ((t (:foreground "#00ffff"))))
 '(sly-mrepl-input-face ((t (:bold t :weight bold))))
 '(sly-mrepl-inputed-output-face ((t (:foreground "springgreen")))) 
 '(sly-mrepl-prompt-face ((((class color) (min-colors 89)) :foreground "#Ffa500")))
 '(sly-mrepl-output-face ((((class color) (min-colors 89)) :forground "SteelBlue")))
 '(sly-style-warning-face ((t (:underline "gold"))))
 '(sly-warning-face ((((class color) (min-colors 89)) :forground "coral")))

;;; SLIME stuff
 '(slime-error-face ((t (:underline "red"))))
 '(slime-highlight-edits-face ((t (:background "dimgray"))))
 '(slime-highlight-face ((t (:foreground "yellow" :background "SteelBlue" :underline nil))))
 '(slime-inspector-action-face ((t (:bold t :weight bold :foreground "#8b2252"))))
 '(slime-inspector-label-face ((t (:foreground "#00ff00"))))
 '(slime-inspector-topline-face ((t (nil))))
 '(slime-inspector-type-face ((t (nil))))
 '(slime-inspector-value-face ((t (:foreground "#ffaa00"))))
 '(slime-note-face ((t (:underline "light goldenrod"))))
 '(slime-reader-conditional-face ((t (:foreground "#00ffff"))))
 '(slime-repl-input-face ((t (:bold t :weight bold))))
 '(slime-repl-inputed-output-face ((t (:foreground "springgreen"))))
 '(slime-repl-output-face ((t (:foreground "SteelBlue"))))
 '(slime-repl-output-mouseover-face ((t (:foreground "springgreen" :box (:line-width 1 :color "black" :style released-button)))))
 '(slime-repl-prompt-face ((t (:foreground "Orange"))))
 '(slime-repl-result-face ((t (:foreground "#63b8ff"))))
 '(slime-style-warning-face ((t (:underline "gold"))))
 '(slime-warning-face ((t (:underline "coral"))))
 
 '(spaceline-evil-emacs ((((class color) (min-colors 89)) :inherit deepsky-theme-active-magenta)))
 '(spaceline-evil-insert ((((class color) (min-colors 89)) :inherit deepsky-theme-active-green)))
 '(spaceline-evil-motion ((((class color) (min-colors 89)) :inherit deepsky-theme-active-blue)))
 '(spaceline-evil-normal ((((class color) (min-colors 89)) :background "#a8a8a8" :foreground "#181a20")))
 '(spaceline-evil-replace ((((class color) (min-colors 89)) :inherit deepsky-theme-active-red)))
 '(spaceline-evil-visual ((((class color) (min-colors 89)) :inherit deepsky-theme-active-cyan)))
 '(spaceline-flycheck-error ((((class color) (min-colors 89)) :foreground "#ffa7ba")))
 '(spaceline-flycheck-info ((((class color) (min-colors 89)) :foreground "#00d8b4")))
 '(spaceline-flycheck-warning ((((class color) (min-colors 89)) :foreground "#dbbe5f")))
 '(spaceline-highlight-face ((((class color) (min-colors 89)) :inherit deepsky-theme-fringe-blue)))
 '(spaceline-modified ((((class color) (min-colors 89)) :inherit deepsky-theme-fringe-magenta)))
 '(spaceline-python-venv ((((class color) (min-colors 89)) :foreground "#d5b1ff")))
 '(spaceline-read-only ((((class color) (min-colors 89)) :inherit deepsky-theme-fringe-red)))
 '(spaceline-unmodified ((((class color) (min-colors 89)) :inherit deepsky-theme-fringe-cyan)))
 '(swiper-background-match-face-1 ((((class color) (min-colors 89)) :inherit deepsky-theme-subtle-neutral)))
 '(swiper-background-match-face-2 ((((class color) (min-colors 89)) :inherit deepsky-theme-subtle-cyan)))
 '(swiper-background-match-face-3 ((((class color) (min-colors 89)) :inherit deepsky-theme-subtle-magenta)))
 '(swiper-background-match-face-4 ((((class color) (min-colors 89)) :inherit deepsky-theme-subtle-green)))
 '(swiper-line-face ((((class color) (min-colors 89)) :extend t :inherit deepsky-theme-special-cold)))
 '(swiper-match-face-1 ((((class color) (min-colors 89)) :inherit swiper-line-face)))
 '(swiper-match-face-2 ((((class color) (min-colors 89)) :inherit swiper-line-face)))
 '(swiper-match-face-3 ((((class color) (min-colors 89)) :inherit swiper-line-face)))
 '(swiper-match-face-4 ((((class color) (min-colors 89)) :inherit swiper-line-face)))
 '(table-cell ((((class color) (min-colors 89)) :background "#0f0e39")))
 '(tty-menu-disabled-face ((((class color) (min-colors 89)) :background "#181a20" :foreground "#a8a8a8")))
 '(tty-menu-enabled-face ((((class color) (min-colors 89)) :inherit bold :background "#181a20" :foreground "#ffffff")))
 '(tty-menu-selected-face ((((class color) (min-colors 89)) :inherit deepsky-theme-intense-blue)))
 '(undo-tree-visualizer-active-branch-face ((((class color) (min-colors 89)) :inherit bold :foreground "#ffffff")))
 '(undo-tree-visualizer-current-face ((((class color) (min-colors 89)) :foreground "#00a2ff")))
 '(undo-tree-visualizer-default-face ((((class color) (min-colors 89)) :foreground "#a8a8a8")))
 '(undo-tree-visualizer-register-face ((((class color) (min-colors 89)) :foreground "#ff8bd4")))
 '(undo-tree-visualizer-unmodified-face ((((class color) (min-colors 89)) :foreground "#00fc50")))
 '(vc-conflict-state ((((class color) (min-colors 89)) :inherit deepsky-theme-slant :foreground "#ffa7ba")))
 '(vc-edited-state ((((class color) (min-colors 89)) :foreground "#dbbe5f")))
 '(vc-locally-added-state ((((class color) (min-colors 89)) :foreground "#00d8b4")))
 '(vc-locked-state ((((class color) (min-colors 89)) :foreground "#34cfff")))
 '(vc-missing-state ((((class color) (min-colors 89)) :inherit deepsky-theme-slant :foreground "#d5b1ff")))
 '(vc-needs-update-state ((((class color) (min-colors 89)) :inherit deepsky-theme-slant :foreground "#70d73f")))
 '(vc-removed-state ((((class color) (min-colors 89)) :foreground "#ffa7ba")))
 '(vc-state-base ((((class color) (min-colors 89)) :foreground "#f4f4f4")))
 '(vc-up-to-date-state ((((class color) (min-colors 89)) :foreground "#c6eaff")))
 '(which-key-command-description-face ((((class color) (min-colors 89)) :foreground "#00d3d0")))
 '(which-key-group-description-face ((((class color) (min-colors 89)) :foreground "#f78fe7")))
 '(which-key-highlighted-command-face ((((class color) (min-colors 89)) :foreground "#4ae8fc" :underline t)))
 '(which-key-key-face ((((class color) (min-colors 89)) :inherit bold :foreground "#00a2ff")))
 '(which-key-local-map-description-face ((((class color) (min-colors 89)) :foreground "#ffffff")))
 '(which-key-note-face ((((class color) (min-colors 89)) :background "#110b11" :foreground "#bfebe0")))
 '(which-key-separator-face ((((class color) (min-colors 89)) :foreground "#a8a8a8")))
 '(which-key-special-key-face ((((class color) (min-colors 89)) :inherit bold :foreground "#ffdd00")))
 '(whitespace-big-indent ((((class color) (min-colors 89)) :inherit deepsky-theme-subtle-red)))
 '(whitespace-empty ((((class color) (min-colors 89)) :inherit deepsky-theme-intense-magenta)))
 '(whitespace-hspace ((((class color) (min-colors 89)) :background "#170016" :foreground "#a4959f")))
 '(whitespace-indentation ((((class color) (min-colors 89)) :background "#170016" :foreground "#a4959f")))
 '(whitespace-line ((((class color) (min-colors 89)) :inherit deepsky-theme-special-warm)))
 '(whitespace-newline ((((class color) (min-colors 89)) :background "#170016" :foreground "#a4959f")))
 '(whitespace-space ((((class color) (min-colors 89)) :background "#170016" :foreground "#a4959f")))
 '(whitespace-space-after-tab ((((class color) (min-colors 89)) :inherit deepsky-theme-subtle-magenta)))
 '(whitespace-space-before-tab ((((class color) (min-colors 89)) :inherit deepsky-theme-subtle-cyan)))
 '(whitespace-tab ((((class color) (min-colors 89)) :background "#170016" :foreground "#a4959f")))
 '(whitespace-trailing ((((class color) (min-colors 89)) :inherit deepsky-theme-intense-red)))
 '(window-divider ((((class color) (min-colors 89)) :foreground "#646464")))
 '(window-divider-first-pixel ((((class color) (min-colors 89)) :foreground "#969696")))
 '(window-divider-last-pixel ((((class color) (min-colors 89)) :foreground "#969696")))
 '(xref-file-header ((((class color) (min-colors 89)) :inherit bold :foreground "#c6eaff")))
 '(xref-line-number ((((class color) (min-colors 89)) :foreground "#a8a8a8")))
 '(xref-match ((((class color) (min-colors 89)) :inherit match)))
 '(yas-field-highlight-face ((((class color) (min-colors 89)) :background "#181a20" :foreground "#ffffff")))
 '(line-number-major-tick ((((class color) (min-colors 89)) :inherit (bold default) :background "#221000" :foreground "#dfdfb0")))
 '(line-number-minor-tick ((((class color) (min-colors 89)) :inherit (bold default) :background "#1e1e1e" :foreground "#bfc0c4")))
 '(tab-bar ((((class color) (min-colors 89)) :background "#2c2c2c" :foreground "#ffffff")))
 '(tab-bar-tab ((((class color) (min-colors 89)) :inherit bold :box (:line-width 2 :color "#0e0e0e") :background "#0e0e0e" :foreground "#ffffff")))
 '(tab-bar-tab-inactive ((((class color) (min-colors 89)) :box (:line-width 2 :color "#3d3d3d") :background "#3d3d3d" :foreground "#e0e6f0")))
 '(tab-line ((((class color) (min-colors 89)) :height 0.95 :background "#2c2c2c" :foreground "#ffffff"))))



(provide-theme 'deepsky-modus-fade)
